# Generated by Django 4.2.5 on 2023-09-19 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_dimensions', message='Entry should follow format: 100x100', regex='^[\\d,]+x[\\d,]+$')])),
                ('description', models.TextField(blank=True)),
                ('archive_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('date_authenticated', models.DateField(blank=True)),
                ('first_meeting_date', models.DateField(blank=True)),
                ('second_meeting_date', models.DateField(blank=True)),
                ('date_archived', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('opinion', models.CharField(choices=[('T', 'True'), ('F', 'False'), ('VR', 'Viewing Requested'), ('TE', 'To Examine')], default='TE', max_length=20)),
                ('has_artist_authentication', models.BooleanField(default=False)),
                ('artist_authentication_notes', models.TextField(blank=True)),
                ('work_requested_for_viewing', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthenticationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='authentication_documents')),
            ],
        ),
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_front', models.CharField(choices=[('F', 'Front'), ('B', 'Back')], default='F', max_length=5)),
                ('signature_notes', models.TextField(blank=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_auth.art')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_notes', models.TextField(blank=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_auth.art')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='art_photos')),
                ('photo_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_auth.photoset')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='art_auth.position')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dimensions',
            constraint=models.UniqueConstraint(fields=('height', 'width'), name='unique_dimensions'),
        ),
        migrations.AddField(
            model_name='authenticationdocument',
            name='authentication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_auth.authentication'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_auth.applicant'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='commission',
            field=models.ManyToManyField(to='art_auth.commissioner'),
        ),
        migrations.AddField(
            model_name='art',
            name='created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='art_auth.creationdate'),
        ),
        migrations.AddField(
            model_name='art',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='art_auth.genre'),
        ),
        migrations.AddField(
            model_name='art',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='art_auth.technique'),
        ),
        migrations.AddField(
            model_name='application',
            name='art',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='art_auth.art'),
        ),
        migrations.AddField(
            model_name='application',
            name='authentication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='art_auth.authentication'),
        ),
    ]
