# Generated by Django 4.2.5 on 2023-09-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_auth', '0002_remove_application_art_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='application',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='art',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='art_auth.art'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='authentication',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='art_auth.authentication'),
            preserve_default=False,
        ),
    ]
