# Generated by Django 4.2.5 on 2023-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_auth', '0003_remove_art_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='date_archived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='date_authenticated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='first_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='second_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
