# Generated by Django 4.2.5 on 2023-09-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_auth', '0004_alter_authentication_date_archived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='created',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='description',
        ),
    ]
