# Generated by Django 4.2.5 on 2023-09-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_auth', '0005_rename_created_art_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='on_front',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_set',
        ),
        migrations.AddField(
            model_name='art',
            name='photo_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='art',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='art_auth.art'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.CharField(choices=[('IF', 'In Front'), ('FBD', 'From Behind'), ('LS', 'Left Side'), ('RS', 'Right Side'), ('FA', 'From Above'), ('FBW', 'From Below')], default='IF', max_length=20),
        ),
        migrations.DeleteModel(
            name='PhotoSet',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
