# Generated by Django 4.2.5 on 2023-09-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_auth', '0006_rename_on_front_signature_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_auth.art')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_auth.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='art',
            field=models.ManyToManyField(through='art_auth.Ownership', to='art_auth.art'),
        ),
    ]
