# Generated by Django 4.2.5 on 2023-09-15 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 15, 30, 26, 201865, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
